# Generated by Django 4.2.13 on 2024-06-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('FI', 'Finance Officer'), ('AD', 'Admin'), ('MA', 'Manager'), ('LO', 'Loan Officer'), ('OP', 'Operation Manager'), ('AC', 'Accountant')], default='AC', max_length=2),
        ),
    ]
