# Generated by Django 4.2.13 on 2025-04-02 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_profile_role_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('FI', 'Finance Officer'), ('MA', 'Manager'), ('OP', 'Operation Manager'), ('LO', 'Loan Officer'), ('AC', 'Accountant'), ('AD', 'Admin')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
