# Generated by Django 4.2.13 on 2025-04-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_role_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('MA', 'Manager'), ('AD', 'Admin'), ('FI', 'Finance Officer'), ('AC', 'Accountant'), ('LO', 'Loan Officer'), ('OP', 'Operation Manager')], default='AC', max_length=2),
        ),
    ]
