# Generated by Django 4.2.13 on 2025-04-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('FI', 'Finance Officer'), ('AC', 'Accountant'), ('OP', 'Operation Manager'), ('MA', 'Manager'), ('AD', 'Admin'), ('LO', 'Loan Officer')], default='AC', max_length=2),
        ),
    ]
